#!/bin/sh
#
# This file is protected by Copyright. Please refer to the COPYRIGHT file 
# distributed with this source distribution.
# 
# This file is part of GNUHAWK.
# 
# GNUHAWK is free software: you can redistribute it and/or modify is under the 
# terms of the GNU General Public License as published by the Free Software 
# Foundation, either version 3 of the License, or (at your option) any later 
# version.
# 
# GNUHAWK is distributed in the hope that it will be useful, but WITHOUT ANY 
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along with 
# this program.  If not, see http://www.gnu.org/licenses/.
#
 

# Checks command line args
if [[ ${#1} -ne 0 ]] && [ "$1" != "--with-components" ]
then
    echo "reconf: error: unrecognized option: $1"
    echo "to reconf components use: --with-components"
    exit 1
fi

rm -f config.cache

# Setup the libtool stuff
if [ -e /usr/local/share/aclocal/libtool.m4 ]; then
    /bin/cp /usr/local/share/aclocal/libtool.m4 aclocal.d/acinclude.m4
elif [ -e /usr/share/aclocal/libtool.m4 ]; then
    /bin/cp /usr/share/aclocal/libtool.m4 acinclude.m4
fi
libtoolize --force --automake

if [ -d ${OSSIEHOME}/share/aclocal ]; then
    OSSIE_AC_INCLUDE=${OSSIEHOME}/share/aclocal
else
    echo "Error: Cannot find the OSSIE aclocal files. This is not expected!"
fi
# Search in expected locations for the OSSIE acincludes

if [ -n ${OSSIE_AC_INCLUDE} ]; then
    aclocal -I ${OSSIE_AC_INCLUDE}/ossie
else
    aclocal
fi

autoconf
automake --foreign --add-missing

if [ ! -d ./include/gnuhawk ]
then
    mkdir ./include/gnuhawk
fi
if [ ! -d ./include/gnuhawk/gnuradio ]
then
    mkdir ./include/gnuhawk/gnuradio
fi

# gnuradio-core filter include files
topdir=`pwd`
(PYTHONPATH=${topdir}/gnuradio/gnuradio-core/src/python:${PYTHONPATH};cd gnuradio/gnuradio-core/src/lib/filter;python generate_all.py;)
if [ ! -d ./include/gnuhawk/gnuradio/filter ]
then
    mkdir ./include/gnuhawk/gnuradio/filter
fi
# Only copy filter header files that have changed
for i in ./gnuradio/gnuradio-core/src/lib/filter/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/filter/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/filter
    fi
done

# gnuradio-core general include files
if [ ! -d ./include/gnuhawk/gnuradio/general ]
then
    mkdir ./include/gnuhawk/gnuradio/general
fi
# Only copy general header files that have changed
for i in ./gnuradio/gnuradio-core/src/lib/general/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/general/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/general
    fi
done

# gnuradio-core gengen include files
topdir=`pwd`
(PYTHONPATH=${topdir}/gnuradio/gnuradio-core/src/python:${PYTHONPATH}; \
cd gnuradio/gnuradio-core/src/lib/gengen; \
cmake . -DCMAKE_MODULE_PATH=../../../../cmake/Modules; \
python generate_helper.py gr_vector_insert_X gr_vector_insert_X.h.t b; \
python generate_helper.py gr_vector_insert_X gr_vector_insert_X.cc.t b; \
python generate_helper.py gr_add_const_XX gr_add_const_XX.h.t bb; \
python generate_helper.py gr_add_const_XX gr_add_const_XX.cc.t bb; \
python generate_all.py;)

if [ ! -d ./include/gnuhawk/gnuradio/gengen ]
then
    mkdir ./include/gnuhawk/gnuradio/gengen
fi
# Only copy gengen header files that have changed
for i in ./gnuradio/gnuradio-core/src/lib/gengen/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gengen/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gengen
    fi
done

# gnuradio-core hier include files
if [ ! -d ./include/gnuhawk/gnuradio/hier ]
then
    mkdir ./include/gnuhawk/gnuradio/hier
fi
# Only copy hier header files that have changed
for i in ./gnuradio/gnuradio-core/src/lib/hier/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/hier/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/hier
    fi
done

# gnuradio-core io include files
if [ ! -d ./include/gnuhawk/gnuradio/io ]
then
    mkdir ./include/gnuhawk/gnuradio/io
fi
# Only copy io header files that have changed
for i in ./gnuradio/gnuradio-core/src/lib/io/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/io/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/io
    fi
done

# gnuradio-core reed-solomon include files
if [ ! -d ./include/gnuhawk/gnuradio/reed-solomon ]
then
    mkdir ./include/gnuhawk/gnuradio/reed-solomon
fi
# Only copy reed-solomon header files that have changed
for i in ./gnuradio/gnuradio-core/src/lib/reed-solomon/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/reed-solomon/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/reed-solomon
    fi
done

# gnuradio-core runtime include files
if [ ! -d ./include/gnuhawk/gnuradio/runtime ]
then
    mkdir ./include/gnuhawk/gnuradio/runtime
fi
# Only copy runtime header files that have changed
for i in ./gnuradio/gnuradio-core/src/lib/runtime/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/runtime/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/runtime
    fi
done

# gnuradio-core viterbi include files
if [ ! -d ./include/gnuhawk/gnuradio/viterbi ]
then
    mkdir ./include/gnuhawk/gnuradio/viterbi
fi
# Only copy viterbi header files that have changed
for i in ./gnuradio/gnuradio-core/src/lib/viterbi/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/viterbi/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/viterbi
    fi
done

# gruel include files
(cd gnuradio/gruel/src/lib/pmt;python generate_unv.py;)
if [ ! -d ./include/gnuhawk/gnuradio/gruel ]
then
    mkdir ./include/gnuhawk/gnuradio/gruel
fi
# Only copy gruel header files that have changed
for i in ./gnuradio/gruel/src/include/gruel/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gruel/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gruel
    fi
done
for i in ./gnuradio/gruel/src/lib/pmt/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gruel/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gruel
    fi
done

# gr-atsc include files
if [ ! -d ./include/gnuhawk/gnuradio/gr-atsc ]
then
    mkdir ./include/gnuhawk/gnuradio/gr-atsc
fi
# Only copy gr-atsc header files that have changed
for i in ./gnuradio/gr-atsc/src/lib/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-atsc/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-atsc
    fi
done
# Generate extra gr-atsc file
g++ gnuradio/gr-atsc/src/lib/atsci_viterbi_gen.cc -o gnuradio/gr-atsc/src/lib/atsci_viterbi_gen
gnuradio/gr-atsc/src/lib/atsci_viterbi_gen -o gnuradio/gr-atsc/src/lib/atsci_viterbi_mux.cc

# gr-audio include files
if [ ! -d ./include/gnuhawk/gnuradio/gr-audio ]
then
    mkdir ./include/gnuhawk/gnuradio/gr-audio
fi
if [ ! -d ./include/gnuhawk/gnuradio/gr-audio/alsa ]
then
    mkdir ./include/gnuhawk/gnuradio/gr-audio/alsa
fi
# Only copy gr-audio header files that have changed
for i in ./gnuradio/gr-audio/include/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-audio/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-audio
    fi
done
for i in ./gnuradio/gr-audio/lib/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-audio/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-audio
    fi
done
for i in ./gnuradio/gr-audio/lib/alsa/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-audio/alsa/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-audio/alsa
    fi
done
for i in ./gnuradio/gr-audio/lib/oss/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-audio/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-audio
    fi
done

# gr-digital include files
if [ ! -d ./include/gnuhawk/gnuradio/gr-digital ]
then
    mkdir ./include/gnuhawk/gnuradio/gr-digital
fi
# Only copy gr-digital header files that have changed
for i in ./gnuradio/gr-digital/include/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-digital/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-digital
    fi
done

# gr-fcd include files
if [ ! -d ./include/gnuhawk/gnuradio/gr-fcd ]
then
    mkdir ./include/gnuhawk/gnuradio/gr-fcd
fi
# Only copy gr-fcd header files that have changed
for i in ./gnuradio/gr-fcd/include/fcd/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-fcd/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-fcd
    fi
done
for i in ./gnuradio/gr-fcd/lib/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-fcd/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-fcd
    fi
done
for i in ./gnuradio/gr-fcd/lib/fcd/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-fcd/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-fcd
    fi
done
for i in ./gnuradio/gr-fcd/lib/hid/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-fcd/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-fcd
    fi
done

# gr-fft include files
if [ ! -d ./include/gnuhawk/gnuradio/gr-fft ]
then
    mkdir ./include/gnuhawk/gnuradio/gr-fft
fi
if [ ! -d ./include/gnuhawk/gnuradio/gr-fft/fft ]
then
    mkdir ./include/gnuhawk/gnuradio/gr-fft/fft
fi
# Only copy gr-fft header files that have changed
for i in ./gnuradio/gr-fft/include/fft/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-fft/fft/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-fft/fft
    fi
done
for i in ./gnuradio/gr-fft/lib/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-fft/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-fft
    fi
done

# gr-filter include files
topdir=`pwd`
(cd gnuradio/gr-filter/include/filter;\
 cmake . -DCMAKE_MODULE_PATH=../../../cmake/Modules; \
 PYTHONPATH=${topdir}/gnuradio/gnuradio-core/src/python:${PYTHONPATH}; \
 python generate_helper.py fir_filter_XXX fir_filter_XXX.h.t ccc ccf fcc fff fsf scc; \
 python generate_helper.py freq_xlating_fir_filter_XXX freq_xlating_fir_filter_XXX.h.t ccc ccf fcc fcf scf scc; \
 python generate_helper.py interp_fir_filter_XXX interp_fir_filter_XXX.h.t ccc ccf fcc fff fsf scc; \
 python generate_helper.py rational_resampler_base_XXX rational_resampler_base_XXX.h.t ccc ccf fcc fff fsf scc; \
)

(cd gnuradio/gr-filter/lib;\
 cmake . -DCMAKE_MODULE_PATH=../../cmake/Modules; \
 PYTHONPATH=${topdir}/gnuradio/gnuradio-core/src/python:${PYTHONPATH}; \
 python generate_helper.py fir_filter_XXX_impl fir_filter_XXX_impl.cc.t ccc ccf fcc fff fsf scc; \
 python generate_helper.py fir_filter_XXX_impl fir_filter_XXX_impl.h.t ccc ccf fcc fff fsf scc; \
 python generate_helper.py freq_xlating_fir_filter_XXX_impl freq_xlating_fir_filter_XXX_impl.cc.t ccc ccf fcc fcf scf scc; \
 python generate_helper.py freq_xlating_fir_filter_XXX_impl freq_xlating_fir_filter_XXX_impl.h.t ccc ccf fcc fcf scf scc; \
 python generate_helper.py interp_fir_filter_XXX_impl interp_fir_filter_XXX_impl.cc.t ccc ccf fcc fff fsf scc; \
 python generate_helper.py interp_fir_filter_XXX_impl interp_fir_filter_XXX_impl.h.t ccc ccf fcc fff fsf scc; \
 python generate_helper.py rational_resampler_base_XXX_impl rational_resampler_base_XXX_impl.cc.t ccc ccf fcc fff fsf scc; \
 python generate_helper.py rational_resampler_base_XXX_impl rational_resampler_base_XXX_impl.h.t ccc ccf fcc fff fsf scc; \
)

if [ ! -d ./include/gnuhawk/gnuradio/gr-filter ]
then
    mkdir ./include/gnuhawk/gnuradio/gr-filter
fi
if [ ! -d ./include/gnuhawk/gnuradio/gr-filter/filter ]
then
    mkdir ./include/gnuhawk/gnuradio/gr-filter/filter
fi
# Only copy gr-filter header files that have changed
for i in ./gnuradio/gr-filter/include/filter/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-filter/filter/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-filter/filter
    fi
done
for i in ./gnuradio/gr-filter/lib/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-filter/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-filter
    fi
done

# gr-howto-write-a-block include files
if [ ! -d ./include/gnuhawk/gnuradio/gr-howto-write-a-block ]
then
    mkdir ./include/gnuhawk/gnuradio/gr-howto-write-a-block
fi
# Only copy gr-howto-write-a-block header files that have changed
for i in ./gnuradio/gr-howto-write-a-block/include/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-howto-write-a-block/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-howto-write-a-block
    fi
done

# gr-noaa include files
if [ ! -d ./include/gnuhawk/gnuradio/gr-noaa ]
then
    mkdir ./include/gnuhawk/gnuradio/gr-noaa
fi
# Only copy gr-noaa header files that have changed
for i in ./gnuradio/gr-noaa/lib/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-noaa/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-noaa
    fi
done

# gr-pager include files
if [ ! -d ./include/gnuhawk/gnuradio/gr-pager ]
then
    mkdir ./include/gnuhawk/gnuradio/gr-pager
fi
# Only copy gr-pager header files that have changed
for i in ./gnuradio/gr-pager/lib/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-pager/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-pager
    fi
done

# gr-trellis include files
topdir=`pwd`
(PYTHONPATH=${topdir}/gnuradio/gnuradio-core/src/python:${PYTHONPATH};cd gnuradio/gr-trellis/src/lib;python generate_all.py;)
if [ ! -d ./include/gnuhawk/gnuradio/gr-trellis ]
then
    mkdir ./include/gnuhawk/gnuradio/gr-trellis
fi
# Only copy gr-noaa header files that have changed
for i in ./gnuradio/gr-trellis/src/lib/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-trellis/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-trellis
    fi
done

# gr-vocoder include files
if [ ! -d ./include/gnuhawk/gnuradio/gr-vocoder ]
then
    mkdir ./include/gnuhawk/gnuradio/gr-vocoder
fi
if [ ! -d ./include/gnuhawk/gnuradio/gr-vocoder/codec2 ]
then
    mkdir ./include/gnuhawk/gnuradio/gr-vocoder/codec2
fi
if [ ! -d ./include/gnuhawk/gnuradio/gr-vocoder/g7xx ]
then
    mkdir ./include/gnuhawk/gnuradio/gr-vocoder/g7xx
fi
if [ ! -d ./include/gnuhawk/gnuradio/gr-vocoder/gsm ]
then
    mkdir ./include/gnuhawk/gnuradio/gr-vocoder/gsm
fi
# Only copy gr-vocoder header files that have changed
for i in ./gnuradio/gr-vocoder/include/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-vocoder/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-vocoder
    fi
done
for i in ./gnuradio/gr-vocoder/lib/codec2/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-vocoder/codec2/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-vocoder/codec2
    fi
done
for i in ./gnuradio/gr-vocoder/lib/g7xx/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-vocoder/g7xx/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-vocoder/g7xx
    fi
done
for i in ./gnuradio/gr-vocoder/lib/gsm/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-vocoder/gsm/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-vocoder/gsm
    fi
done

# gr-wavelet include files
if [ ! -d ./include/gnuhawk/gnuradio/gr-wavelet ]
then
    mkdir ./include/gnuhawk/gnuradio/gr-wavelet
fi
# Only copy gr-wavelet header files that have changed
for i in ./gnuradio/gr-wavelet/lib/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-wavelet/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-wavelet
    fi
done
for i in ./gnuradio/gr-wavelet/include/wavelet/*.h
do
    diff ${i} "./include/gnuhawk/gnuradio/gr-wavelet/"$(basename ${i}) >& /dev/null
    if [[ $? != 0 ]];
    then
        cp ${i} ./include/gnuhawk/gnuradio/gr-wavelet
    fi
done

# reconf for each component
if [ "$1" == "--with-components" ];
then

    # build components testing
    ( cd components; ./reconf)

    # build components for QA testing
    ( cd qa; ./reconf)

fi
